CREATE OR REPLACE TABLE DIM_SELLERS (
    SELLER_ID VARCHAR(50) PRIMARY KEY,
    SELLER_ZIP_CODE_PREFIX VARCHAR(20),
    SELLER_CITY VARCHAR(100),
    SELLER_STATE VARCHAR(10),
    SELLER_LAT FLOAT,
    SELLER_LNG FLOAT,
    HAS_GEO BOOLEAN
);