CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID INT PRIMARY KEY,
    FULL_DATE DATE,
    YEAR INT,
    MONTH INT,
    MONTH_NAME VARCHAR(15),
    QUARTER INT,
    WEEK_OF_YEAR INT,
    DAY_OF_MONTH INT,
    DAY_OF_WEEK INT,
    DAY_NAME VARCHAR(15),
    IS_WEEKEND BOOLEAN,
    YEAR_MONTH VARCHAR(10),
    YEAR_QUARTER VARCHAR(10)
);