CREATE OR REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_ID VARCHAR(50) PRIMARY KEY,
    PRODUCT_CATEGORY_NAME VARCHAR(100),
    PRODUCT_NAME_LENGTH FLOAT,
    PRODUCT_DESCRIPTION_LENGTH FLOAT,
    PRODUCT_PHOTOS_QTY FLOAT,
    PRODUCT_WEIGHT_G FLOAT,
    PRODUCT_LENGTH_CM FLOAT,
    PRODUCT_HEIGHT_CM FLOAT,
    PRODUCT_WIDTH_CM FLOAT,
    PRODUCT_VOLUME_CM3 FLOAT,
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(100),
    SIZE_CATEGORY VARCHAR(50),
    HAS_MISSING_DIMENSIONS BOOLEAN
);