CREATE OR REPLACE TABLE DIM_CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_UNIQUE_ID VARCHAR(50),
    CUSTOMER_ZIP_CODE_PREFIX VARCHAR(20),
    CUSTOMER_CITY VARCHAR(100),
    CUSTOMER_STATE VARCHAR(10),
    CUSTOMER_STATE_VALID VARCHAR(10),
    CUSTOMER_LAT FLOAT,
    CUSTOMER_LNG FLOAT,
    HAS_GEO BOOLEAN
);